### ISSUE TITLE
[BUG] valid aspect models cannot be uploaded in newest versions of editor

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-aspect-model-editor#107]
**How: List of performed steps**

I just wanted to view the released aspect model 
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl
from Catena-X/Tractus-X in the aspect model editor

Steps taken:
1) Opening with Editor Version 5.0 leads to errors, model is not loaded at all
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/59824205/e39bfd11-4981-4c9b-9705-0482e16b60fb)

2) Opening with Editor Version 4.6.0 leads to errors, model is not loaded at all
3) Opening with Editor Version 4.5.0 is ok and works, errors but model is loaded

Opening means: 
1) "copy all/alles auswählen" text of [raw file in github](https://raw.githubusercontent.com/eclipse-tractusx/sldt-semantic-models/main/io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl) from Tractus-X 
2) Open Editor, Dismiss
3) press New/Load Button
4) copy text from step 1) into the window of "Start modeling"
5) press "start modeling"

This is also what is explicitly requested in Catena-X:
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main 
`**Currently, we assume the usage of the version 2.3.1 of the [SAMM-CLI](https://eclipse-esmf.github.io/esmf-developer-guide/2.3.1/tooling-guide/samm-cli.html) and version 4.5.0 of the [Aspect Model Editor](https://eclipse-esmf.github.io/ame-guide/4.5.0/introduction.html) **.`

Expected Behaviour:

- aspect model should be able to be uploaded in every 4.* Version of the editor
- aspect model should be automatically migrated if needed with corresponding messages

This is how it looks like in Version 4.5 - like expected since there are two shared models in it
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/59824205/fa7120df-ef73-4d24-a717-c563fafa14ad)

**Comment by michelu89** [comment]
Thank you for bringing this to our attention. We're taking the following steps to address the issue:

**Error Message Enhancement:** 

We are updating our error messages to more accurately describe the problem and provide clear guidance on how to resolve it. These detailed messages will appear in the notification's details section for better visibility and understanding.

**Follow-Up Improvement [(Adding warning dialog)](https://github.com/eclipse-esmf/esmf-aspect-model-editor/issues/108
) :** 

We have launched a issue to further improve the system. A key point of focus is the handling of aspect models with missing elements. This issue, particularly observed in version 4.x.x, often leads to overlooked element references and can cause recurring errors. Our aim is to ensure these critical elements are accurately tracked and managed to prevent such issues in the future.

Your feedback is invaluable in helping us enhance our system, and we're committed to continually improving our processes and features.
