### ISSUE TITLE
[Task] Minor issues in Documentation for Help

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-aspect-model-editor#111]
**Is your task related to a problem? Please describe.**
When opening the ditor and clicking on help (right upper corner) I get:

![2023-11-13_14h03_11](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/59824205/32407a95-07fc-4f5c-9c3c-34b895d86621)

**Describe the solution you'd like**
Substitute "Digital Twin System" by "Eclipse Semantic Modeling Framework"

**Comment by michelu89** [comment]
We have changed this dialog in https://github.com/eclipse-esmf/esmf-aspect-model-editor/pull/116 and this will available in version 5.1.2.
