### ISSUE TITLE
How to install / run locally?

### ISSUE THREAD

**Issue by matgnt** [eclipse-esmf/esmf-aspect-model-editor#117]
I followed the instructions mentioned in the setup section
https://github.com/eclipse-esmf/esmf-aspect-model-editor?tab=readme-ov-file#setup

First I figured out that my nodejs version seemd to be to old. Instead of the system NodeJs, I then used v21 and I could run the `npm insall`.

When I start the editor with `npm run start` I get the UI.

When I try to create an aspect, nothing happens. Also the command line doesn't show any logs.
![Screenshot from 2024-01-08 16-19-38](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/198707/9292f853-cc47-4f13-9eda-78a2c6a7f6aa)
After confirming with 'create' there is no item visible and no log output.

System: Debian Linux

Any ideas?

**Comment by matgnt** [comment]
or is there a docker / docker-compose file available anywhere? Couldn't find one.

**Comment by waltersve** [comment]
Hi Matthias, that is only required if you want to build it from scratch to maybe extend the editor. Contributions always welcome. For only install it and use it you can find here the installable versions for windows, linux and mac: https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.1.1

**Comment by chris-volk** [comment]
Hi @matgnt , 
Thanks for opening the issue. I guess you just to use the editor?
As @waltersve mentioned, get the linux installer from /releases .
We shall update the readme (see https://github.com/eclipse-esmf/esmf-aspect-model-editor/pull/118 )

**Comment by matgnt** [comment]
Thanks for the information! I may contribute a docker-compose setup for people who don't want to install, but just run it locally.

Do I understand this right, that you need the backend from here
https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend
to make the editor work? If yes, where can I find information how those are connected?
I just saw, that the release contains a huge 'backend' blob.
I couldn't find anything in the Readme and also the Developer documentation link didn't show more information regarding this.

Thanks for your help,
Matthias Binzer

**Comment by pavel-s-epam** [comment]
Hi @matgnt, thanks for your question.

Yes, the respective backend for the editor lives in https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend repo and it's required for running Aspect Model Editor locally in development mode.

Regarding a connection between the frontend and backend, I'm not sure if it's documented somewhere at the moment (as @chris-volk mentioned earlier, the readme shall be updated) because it's quite simple: starting both parts should be sufficient for the app to work (the frontend is already configured to communicate through the `9091` port which AME backend is running on by default).

**Comment by matgnt** [comment]
Thanks @pavel-s-epam  . Since in docker-compose, the 2 systems (frontend and backend) would have different hostnames. How can I configure the frontend to use a different hostname and port? As you mentioned, this could go into the Readme.

**Comment by pavel-s-epam** [comment]
> Thanks @pavel-s-epam . Since in docker-compose, the 2 systems (frontend and backend) would have different hostnames. How can I configure the frontend to use a different hostname and port? As you mentioned, this could go into the Readme.

For the client side, the configuration can be found in https://github.com/eclipse-esmf/esmf-aspect-model-editor/blob/main/core/libs/shared/src/lib/config.ts, and probably the port should be additionally adjusted [here](https://github.com/eclipse-esmf/esmf-aspect-model-editor/blob/main/core/electron-libs/core.js#L51) as well.

For the server side, the corresponding configuration files are stored in the following folder: https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend/tree/main/src/main/resources.

Please, let us know if these instructions worked for you, in that case we will include them into the readme.

**Comment by michelu89** [comment]
Hi @matgnt,

Pavel has already pointed out the correct information, but please note that the path for the Backend Properties has changed. You can find the new path here: https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend/tree/main/aspect-model-editor-runtime/src/main/resources. 

Alternatively, you can directly run the binary available under our Releases section: https://github.com/eclipse-esmf/esmf-aspect-model-editor-backend/releases. This allows you to start the backend immediately in the terminal and choose your preferred port `ame-backend-<VERSION>-<OS> -Dserver.port=<PORT>`. For the frontend, the port must of course be changed independently as Pavel mentioned.

We will be updating the README accordingly to make this clearer for developers. 

Thank you for your comment!
