### ISSUE TITLE
[Task] Make version-less documentation link available

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-aspect-model-editor#12]
There should be a link to the Aspect Model Editor documentation that does not include the version in its URL (so it stays valid and always points to the latest version):
https://openmanufacturingplatform.github.io/sds-documentation/sds-documentation/index.html

It should be set up so that in `antora.yml` on the main branch, the `version` attribute is always the fixed string "master" (see [component version with no version](https://docs.antora.org/antora/2.3/component-with-no-version/)), and in `antora.yml` in each tagged version, the `version` attribute contains the version string for this tag.

For example, this is the link to antora.yml on main, this should contain `version: "master"`:
https://github.com/OpenManufacturingPlatform/sds-aspect-model-editor/blob/main/documentation/ame-guide/antora.yml

This is the link to antora.yml on the 4.0.1 tag, this should contain (and does already) `version: "4.0.1"`:
https://github.com/OpenManufacturingPlatform/sds-aspect-model-editor/blob/v4.0.1/documentation/ame-guide/antora.yml

Furthermore, the site configuration in the sds-documenation needs to be adjusted to not exclude all branches, but instead to include the main branch:
https://github.com/OpenManufacturingPlatform/sds-documentation/blob/main/site.yml#L20

**Comment by michelu89** [comment]
Already fixed.
