### ISSUE TITLE
[BUG] Export Aspect Model messes up language tags of exampleValue in 5.1.0

### ISSUE THREAD

**Issue by FlorianPatzerC0d3** [eclipse-esmf/esmf-aspect-model-editor#121]
**How: List of performed steps**
Load this adjusted default model with a multi language text example value:
[Test-AspectDefaultLangTag-healthy.txt](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/13964210/Test-AspectDefaultLangTag-healthy.txt)
Export the model.
Try to import it again (will fail).

**What: Actual result vs expected result**
You get this from the export: [Test-AspectDefaultLangTag-MessedUpExport.txt](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/13964211/Test-AspectDefaultLangTag-MessedUpExport.txt)
Instead of `@en` the example value's language tag is just `@`, which is obviously not a valid tag.

**Where: (e.g. component, version, url, your system info)**
AME version 5.1.0, Windows

**Comment by chris-volk** [comment]
Dear @FlorianPatzerC0d3 , thanks for letting us know. We have also found out internally (no github issue) and will fix it for the next version (link to pull request will be put here)

**Comment by michelu89** [comment]
Is fixed in [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).
