### ISSUE TITLE
[BUG] Cannot create payload of Model with DayTimeDuration Characteristic

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#123]
**How: List of performed steps**

- Load [Aspect.ttl.txt](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/14038996/Aspect.ttl.txt)
into editor --> valid model
- create JSON sample payload

**What: Actual result vs expected result**
- should generate payload, but fails with: 
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/a2b748aa-b86c-4182-beae-6737a5cf46ed)

**Where: (e.g. component, version, url, your system info)**
AME 5.1.1

**Comment by michelu89** [comment]
Is fixed in [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).
