### ISSUE TITLE
[Task] Redesign UI with file menu for more intuitive handling of multiple aspect models

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#124]
Since the implementation of the feature to open multiple models in multiple Aspect Model Editor windows, it has become increasingly important to have an intuitive structure for opening/closing files as well as other features.

To make it more intuitive for users, the following redesigns should be considered:

- Implement a file menu (like many text editors have it) and offer to toggle the current toolbar for maximizing the diagram area (offer only the functions that affect the current model in the toolbar)
- Improve the new window opening and file loading by offering to load an empty model, explicitly name the copy paste (from clipboard) function and renaming the AspectDefault to SimpleAspect
- Improve the workspace view by offering expand/collapse toggle and search
- Improve the design of any other tools, e.g. mini map toggle
- Improved file search and element search
- Make the entire design sleek and intuitive

**Comment by michelu89** [comment]
New redesign in [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).
