### ISSUE TITLE
[BUG] Broken empty popup when deleting via del key

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#125]
**How: List of performed steps**
- Create / Load a model with a unit reference, e.g. 
[Aspect.ttl.txt](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/14041012/Aspect.ttl.txt)
- Select the unit reference, in the example the day
- hit the delete key
**What: Actual result vs expected result**
- expected: same as if hitting the delete icon from the toolbar, one can delete the element
- actual: an empty/broken popup: 
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/78f547f4-7687-4bd3-b2ae-efaf9cac091b)

**Where: (e.g. component, version, url, your system info)**
AME 5.1.1 on Win

**Comment by michelu89** [comment]
can you check [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).

If the issue has been resolved, please feel free to close this issue.

**Comment by chris-volk** [comment]
checked and confirmed, thank you.
