### ISSUE TITLE
[BUG] Workspace frame hidden before user action

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#126]
**How: List of performed steps**
- Open AME
- Open the worksapce in the left frame

**What: Actual result vs expected result**
- The frame is empty, only after a user action like scrolling it is shown again

**Where: (e.g. component, version, url, your system info)**
AME 5.1.1 on Win

**Comment by michelu89** [comment]
@chris-volk can you check [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).

If the issue has been resolved, please feel free to close this issue.

**Comment by michelu89** [comment]
Now Released! Check out version 5.4.0 here: [Release v5.4.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.4.0)
