### ISSUE TITLE
[BUG] Generating html doc leads to server error

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#128]
**How: List of performed steps**
- Load/create any valid Aspect Model, e.g. 
[Aspect.ttl.txt](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/14041127/Aspect.ttl.txt)
- generate html doc

**What: Actual result vs expected result**
- the generic "server error" occurs

**Where: (e.g. component, version, url, your system info)**
AME 5.1.1 on Windows 10

**Comment by michelu89** [comment]
This is fixed by v5.2.0.
