### ISSUE TITLE
[BUG] mxGraph'error when open an external element: "The element you are looking for was not found" 

### ISSUE THREAD

**Issue by KobOp** [eclipse-esmf/esmf-aspect-model-editor#135]
**How: List of performed steps**
1. open New window with a default aspect model
2. add an external property from the workspace, e.g. isMoving from Movement.ttl
3. double click on the external property to open a new window showing the external model

**What: Actual result vs expected result**

Actual:
- A new window was opened, then there was a red error message box showing "The element you are looking for was not found".
- No further information is given, the model was successfully validated. This confused the user if his model has an error or not.

Expected:
- The selected property should be automatically focused in the center of the screen, with no error.
- If the selected property is not found, the UI error should be more subtle with a less-alarm color or an icon to notify that this is the UI error, has nothing to do with the content of the model.

**Where: (e.g. component, version, url, your system info)**

Windows10 64bit
AME version: 5.1.1, 5.2.0
SAMM version: 2.1.0
ESMF SDK version: 2.4.2

**Additional context (e.g. references)**
The error seems to be originated from mxGraph lib:
https://github.com/eclipse-esmf/esmf-aspect-model-editor/blob/main/core/libs/mx-graph/src/lib/services/mx-graph.service.ts#L256
The error itself is not critical, thus the error message can be suppressed.

**Comment by KobOp** [comment]
This is an example model. I also tried with newly created model and can reproduce the same error.
[diagnostic.zip](https://github.com/eclipse-esmf/esmf-aspect-model-editor/files/14209913/diagnostic.zip)

**Comment by michelu89** [comment]
Error fixed in [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0).
