### ISSUE TITLE
[Task] Display and edit payloadName

### ISSUE THREAD

**Issue by DrDanielMetz** [eclipse-esmf/esmf-aspect-model-editor#138]
In the semantic aspect meta model it is possible to use payloadNames:
https://docs.bosch-semantic-stack.com/samm-specification/snapshot/modeling-guidelines.html#payload-names

However, those are currently not displayed in the editor nor can they be edited.

It would be nice if the payloadName can be displayed in the properties of a property and maybe - at best - can be edited there.

**Comment by chris-volk** [comment]
.

**Comment by DrDanielMetz** [comment]
@chris-volk:
Ok, thanks!
Yes, it helps!
