### ISSUE TITLE
[BUG] Generated AASX-File can't be loaded into AASPE

### ISSUE THREAD

**Issue by foprs** [eclipse-esmf/esmf-aspect-model-editor#164]
**How: 
Modeled a simple model (Aspekt, Property & Characteristic) -> Generate -> AASX

Generated AASX-File can't be loaded into AASPE. When trying to unzip the AASX (*.zip) the Zip-File is not a valid zip-File.

Version: [v5.3.0-rc3](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0-rc3)
System: Windows 11

**Comment by michelu89** [comment]
Hi @foprs,

Version 5.3.0-rc3 and [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0) both utilize [SDK Version 2.5.1](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.5.1), which contributes to this issue.

[SDK Version 2.6.0](https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.6.0), set to be integrated in the next release of the Aspect Model Editor (AME) in approximately one to two weeks, includes changes to the generation of AASX models. This version leverages the latest AAS4J v1.0.0 and will generate AASX models that address and fix this issue.

**Comment by chris-volk** [comment]
FYI, AME 5.3.0 does not fix this issue yet, we plan to release this SDK 2.6.0 (or later) support with the next AME release (5.3.1 or 5.4.0) to be released soon (new estimated release date next week - apologies for the delay)

**Comment by michelu89** [comment]
Now Released! Check out version 5.4.0 here: [Release v5.4.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.4.0)
