### ISSUE TITLE
[BUG] Generate HTML documentation server error

### ISSUE THREAD

**Issue by CarlyBabee** [eclipse-esmf/esmf-aspect-model-editor#165]
**How: List of performed steps**
- Select Generate HTML documentation in Generate document list
- Select english language
- Click either Open Documentation or Download Documentation buttons
- Server Error

- Select German language
- Click Open Documentation button
- Blank window generated

- Select German language
- Click Download Documentation
- Empty html file downloaded

**What: Actual result vs expected result**
- Actual: Server error
- Expected: Downloaded documentation

**Where: (e.g. component, version, url, your system info)**

**Input (files/screenshots)**

**Output (files/screenshots)**

**Additional context (e.g. references)**

**Comment by michelu89** [comment]
Hey @CarlyBabee, 

Please verify the generation in [v5.3.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.3.0). If the issue persists, could you please provide more detailed information:

- Which operating system are you using?
- Which version of the Aspect Model Editor (AME) are you on?

If the issue has been resolved, please feel free to close this issue.

**Comment by chris-volk** [comment]
On 5.3.0, the html doc generation does not work for Movement (both download and open do not lead to a result), even though the SimpleAspect html doc generation works. Please also address within this issue.

**Comment by michelu89** [comment]
Now Released! Check out version 5.4.0 here: [Release v5.4.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.4.0)
