### ISSUE TITLE
[BUG] Cannot change version of Aspect Model

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#174]
**How: List of performed steps**

- open a model that is already persisted in your workspace
- change something
- go to settings->namespace to chose a new version

**What: Actual result vs expected result**
Expected: 
- When confirming to change version of aspect model in namespace dialog and clicking save, already saved new version to filesystem (test on windows!)
- Do not delete previous version (if deleting previous version is intended, user can do it manually. as a convenience, there could be the secondary option of move instead of save, but not required, the user could manually delete a previous version in the rare case this is required)

Actual:
- One has to save again to workspace after confirming to change the version -> remove dialog to confirm update, then it is obvious to the user they sttill have to save the model to the workspace
- After changing the version, the new version cannot be found in the workspace (even though the right arrow indicates "The file is currently open in this window"), but is in the old version
- Previous version is deleted (should be copy instead)

Additionally it should be checked that it is documented that this is the way to change the version of an Aspect Model (it's a bit hidden, more intuitive would be in the save dialog to have a save vs a save as where the current version could be the default text that can be changed in place --- if this would be a simple thing to add, then this should be done as well)

**Where: (e.g. component, version, url, your system info)**

**Input (files/screenshots)**

**Output (files/screenshots)**

**Additional context (e.g. references)**

**Comment by michelu89** [comment]
Now Released! Check out version 5.4.0 here: [Release v5.4.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.4.0)
