### ISSUE TITLE
Unable to load/import the aspect model (.ttl) file 

### ISSUE THREAD

**Issue by Harishrsharma** [eclipse-esmf/esmf-aspect-model-editor#205]
**How: List of performed steps**
I have extended the Movement aspect model and saved , later when i try to reopen the file this was showing error down here

**What: Actual result vs expected result**
-Validation succeeded, but an error was found while processing the model. This indicates an error in the model validation

- Could not load Aspect model, please make sure the model is valid: null

**Where: (e.g. component, version, url, your system info)**

**Input (files/screenshots)**

**Output (files/screenshots)**
![output_Aspect_modeler](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/70387247/784ceb08-8812-47b5-be4d-fe7024798941)

**Additional context (e.g. references)**
We are also unable to open other files which are a little more complex in aspect model editor

**Comment by michelu89** [comment]
Hey @Harishrsharma , could you provide us with more details on this?

Please specify which version of the Aspect Model Editor was used and, if possible, provide a brief aspect model so that we can accurately replicate the issue.

**Comment by chris-volk** [comment]
Dear @Harishrsharma , we were unfortunately not able to reproduce the issue without receiving the ttl file of the modified Movement model from you. Please reopen if you are able to provide it. Thank you.
