### ISSUE TITLE
[BUG] Upon first start icon toolbar hidden (Linux)

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#220]
**How: List of performed steps**
Download & start AME

**What: Actual result vs expected result**
Toolbar hidden, but upon first start I need the toolbar so that I know what I can do with AME.

**Where: (e.g. component, version, url, your system info)**
Found on @atextor 's machine (OSD 6/Ubuntu 20.04)

**Input (files/screenshots)**
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/307cc135-6229-4091-9c09-e90e0d60c963)

**Comment by chris-volk** [comment]
@atextor , did you install a previous version? Default is only off since around Feb 2024. You can delete your Electron cache manually to test (it is a feature to not reset the cache with every new AME version). FYI @michelu89 .

**Comment by atextor** [comment]
Yes, I also had previous versions installed in the past. Since this is easily resolved, the issue can be closed.
