### ISSUE TITLE
Redundancy of MIME Shared characteritics after reopening the .ttl  

### ISSUE THREAD

**Issue by EliasGitHub-ops** [eclipse-esmf/esmf-aspect-model-editor#233]
**How: List of performed steps**

- Create multiple properties
- Make them share same MIME Characteristic
- Validate the file
- Save the file into workspace
- Re-open the file
- Redundancy of the MIME Characteristic

**What: Actual result vs expected result**
Actual Result: Finding MIME characteristics number equivalent to the properties
Expected Result: One MIME characteristic should be shared by multiple properties

**Where: (e.g. component, version, url, your system info)**
SAMM 2.1.0

**Before**

![MIME BEFORE](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/150354347/a6a64668-1c51-498d-bb52-74b689b6da7b)

**After**
![MIME AFTER](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/150354347/473fdaef-32fd-460c-a5c8-69b146921d55)

**Comment by EliasGitHub-ops** [comment]
Dear @chris-volk, thank you for reaching out to me. The version I am using is as follow:
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/150354347/637ec3a8-edbd-4967-9870-233f7e0c8a5b)

**Comment by chris-volk** [comment]
Dear @EliasGitHub-ops, 
there is indeed one box per usage of a reference after loading an Aspect Models.
This may appear redundant, but has the following advantages: 

- Having only one reference could result in multiple visual intersections depending on the structure of the Aspect Model making it harder to read
- one box per usage is the closest correspondence to what is persisted in the ttl: each time it is one short code block with the full name of the referred element (namespace+name)
- It is not possible to "change" the reference in the current file itself, it's only possible (and intended) to replace one reference with something else in one usage.

Now, you may wonder, why is it not always like this? Well, when you are creating a reference and use it (connect) twice or more often, it could appear strange and lead to confusion if the editor immediately created one box per usage.

Hence we decided to go with this compromise. I will close the issue, but please feel free to further comment and/or reopen.
