### ISSUE TITLE
[BUG] Elements cannot be connected

### ISSUE THREAD

**Issue by paoespinozarias** [eclipse-esmf/esmf-aspect-model-editor#234]
**How: List of performed steps**
- Load a model (To illustrate the issue I use the SimpleAspect.ttl example available in AME):
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/16767406/8a04df13-5e90-4ee1-9061-52b6427e453b)

- Add an element using the drag and drop functionality (In this case I added "Entity1" and previously removed the default "string" datatype from "Characteristic1" ):
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/16767406/8b0c3c84-5145-49f7-9fa2-ad4fc47a9c27)

- Try to connect two elements by using the context menu (right mouse click) to access the action items:
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/16767406/66e4dbde-7719-4f0c-b5f9-d2964eb8e6e2)

**What: Actual result vs expected result**

_Expected_:
Both elements connected 
_Actual_:
Clicking the "connect" option from the context menu doesn't work.

**Where: (e.g. component, version, url, your system info)**
AME 5.5.0 on Windows

**Additional context (e.g. references)**
I have used the SimpleAspect.ttl model to illustrate this issue because I have tested the "connect" functionality and it does not work with this basic model either. In my real scenario I need to reuse a property from another model but I cannot connect the property to my current model.

Finally, I also tried to connect elements using the option available in the "Edit" menu but it doesn't work either (it appears as disabled):
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/16767406/7656c8e9-1df5-45d9-bb4a-ee40f99a849e)

**Comment by michelu89** [comment]
Hey @paoespinozarias,

Please try our latest version: [ESMF Aspect Model Editor v5.6.0](https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v5.6.0).

You can also use the toolbar in the app menu under "View > Toggle Toolbar." It includes several useful features that make it easier to work with the models.
