### ISSUE TITLE
Feature request: Navigate to parent node(s)

### ISSUE THREAD

**Issue by wkl3nk** [eclipse-esmf/esmf-aspect-model-editor#24]
The aspect model is displayed as a graph of nodes and edges.
In the popup-menu on the nodes, I would like to navigate directly to the parent node that references this node.
The screen should scroll, and the parent node should be selected then.
If there are more than only 1 referencing (parent) node, it should be possible to select one of them.

**Comment by chris-volk** [comment]
Thanks for the proposal @wkl3nk . 
We recognize that this is a very useful feature proposal alongside other navigation & connection options that are required for large models and namespaces.
The general requirement is regarding any references whether in the same file or not (reserve links) which is not so simple to provide in a UI.
We are currently working on a solution to connect elements in a large model via type ahead (search by name).
As a follow-up we are going to loo

**Comment by michelu89** [comment]
In the latest version there is a better handling of parent and child elements. https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v4.5.3
