### ISSUE TITLE
[BUG] JSON Schema generation fails when aspect model includes references to other aspects.

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#26]
**Describe the bug**
In AME version 4.2.1:
1. Open/create a model that contains references to elements from other models and is valid
2. Run Generate JSON Schema / Generate sample JSON payload

Expected result: 
JSON Schema / JSON generated

Actual result: "Failed to generate JSON Sample" / Invalid Aspect Model

**Where**
Using the UI functions Generate JSON Schema / Generate sample JSON payload from the toolbar icon "{}" on the top

**Screenshots**
![image](https://user-images.githubusercontent.com/71717528/210821776-f60d2638-be25-4385-acbc-b61bce284a0e.png)

**Comment by chris-volk** [comment]
This issue has been diagnosed as a validation issue in conjunction with the sdk which is fixed in https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.1.1 . 
This issue will therefor be fixed by a pending update of the sdk version within the aspect model editor.

**Comment by chris-volk** [comment]
Until this bug is resolved only a rather inconvenient workaround is available unfortunately: 

1. Manipulating the referenced model
- Open the referenced model from your local workspace within a text editor like notepad++ 
- Delete the aspect element (Careful, this will mean that this Aspect is not available within your workspace anymore)
- Use the https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/tooling-guide/bamm-cli.html to generate the json payload 
(It may also work to do this from within the Aspect Model Editor instead)
2. Merge the referenced model into the referencing model
- Use a text editor like notepad++ to merge the referenced model into the referencing model using text replacements to ensure all elements are defined in the local namespace ":" with unique names, hence avoiding the issue

**Comment by bs-jokri** [comment]
@chris-volk this bug hits also some models in https://github.com/eclipse-tractusx/sldt-semantic-models
Is there already a timeline to fix this? 
I have figured out that the SAMM SDK CLI v2.1.3 can handle such models. Maybe updating to this version is already sufficient.

**Comment by bs-jokri** [comment]
Any updates on this?
