### ISSUE TITLE
[BUG] Windows Installer: Space required is estimated to 0 KB

### ISSUE THREAD

**Issue by knikolas** [eclipse-esmf/esmf-aspect-model-editor#30]
**Describe the bug**
Space required is estimated to 0 KB before installation, after installation it is 412 MB.

**Where**
In the installation wizard for Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/126672745/225062229-5c4435c1-fea7-40d3-b9f5-85ca00b5175d.png)

**Comment by chris-volk** [comment]
Hi @knikolas , thanks for reporting this. If we don't get another comment from you we will assume this occurred in the most recent release https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v4.2.1 .

**Comment by michelu89** [comment]
Will be available in version 5.1.2.
