### ISSUE TITLE
[BUG] Model Abstract Entities not working

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-aspect-model-editor#31]
**Describe the bug**
I tried to model a set of entities. The type of the entity shall be abstract so that different concrete entities can be part of the set.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/59824205/226397046-3126f3e7-e5cf-45e9-880d-be18af289d75.png)

Example:

    set of animals
    animal abstract
    animal derived: dog, cat

This should be possible according to the specification but connection of StatementSet and AbstractStatement is not allowed in the example above.

**Comment by michelu89** [comment]
@BirgitBoss @bs-jokri 

The current implementation is attempting to use the abstract entity "AbstractStatement" as a DataType for "StatementSet". However, this is not permitted according to the SAMM Specification.

The [SAMM Specification's modeling guidelines](https://eclipse-esmf.github.io/samm-specification/2.0.0/modeling-guidelines.html#declaring-abstract-entities) explicitly state that an abstract entity cannot be employed as a DataType for a Characteristic. Hence, the current approach is in conflict with these guidelines and is likely causing the observed issue.

**Comment by BirgitBoss** [comment]
Thanks for clarifying. 

Then this is not a bug but I still see it as useful feature.

**Comment by chris-volk** [comment]
It's intentionally designed in the SAMM specification to ensure (easy validation and) type safety on the json payload (right now the only exception to this is the Either characteristic which is discouraged when it can be avoided for this reason).
For considering to make necessary extensions, can you please outline an example where this is required? We might recommend other modeling approaches (or consider other SAMM extensions) and keep abstract entities abstract. Either in a comment here or directly as a new issue on create an issue in https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/issues and . 

Thanks
