### ISSUE TITLE
[BUG] Can't start release v4.4.1 on Ubuntu

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-esmf/esmf-aspect-model-editor#56]
**Describe the bug**
I can't start release v4.4.1 on Ubuntu

**Where**
Startup

**Screenshots**
- Download the tar.gz for the latest release. 
- Extract program
- Enter program folder
- start the software using following command:
``` sh
# unzip release tar into release folder and cd to release folder
./aspect-model-editor
```
Program returned "child process exited with code 1"

**Additional context**
System: Ubuntu 20.04.6 LTS

If I'm missing something that should be added via a readme / release notes. I meanwhile managed to get the non-release version running and created PR #57 to enhance documentation. That PR does NOT close this issue.

**Comment by smeir** [comment]
I have the same problem on Ubuntu 20.04 LTS and it seems that the backend was linked to a newer not supported glibc.

```
ldd ame-backend.sh 
./ame-backend.sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ame-backend.sh)
./ame-backend.sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ame-backend.sh)
	linux-vdso.so.1 (0x00007ffc47db8000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0e75b2b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0e759dc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0e759c0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0e759a5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0e757b3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0e7e952000)

```

**Comment by chris-volk** [comment]
Thanks for reporting this @smeir , we will adjust the build pipeline to make the editor compatible with older glibc versions.

**Comment by michelu89** [comment]
@smeir 

At the moment, our Linux application supports GLIBC_2.34 and newer versions, since it was compiled using the most recent Ubuntu release.

To avoid any confusion, we'll be updating the executable soon to explicitly indicate the necessary GLIBC version.

**Comment by tom-rm-meyer-ISST** [comment]
Checked release 4.5.1 today. 
- If I start the editor from command line (same as above), it fails with code one again. 
- If I start the aspect-model-editor library from explorer, it doesn't start and I get a popup 'There is no application installed for "shared library" files. Do you want to search for an application to open this file?'. Maybe I missed something to configure?

If I start the backend via the shell script, I get a syntax error:
```
sh backend/ame-backend.sh 
>> backend/ame-backend.sh: 1: Syntax error: "(" unexpected
```

Note: GLIBC version
```
ldd --version
>> ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

**Comment by michelu89** [comment]
@tom-rm-meyer-ISST 

Ive tested this with "Ubuntu 22.04.3 LTS", which currently utilizes GLIBC 2.35. Both the application launch via terminal and the executable start through a double-click worked seamlessly for me.

You might consider updating your Ubuntu version or upgrading GLIBC to 2.35. (This could maybe cause the problem)

As mentioned in a previous comment, our next release will include the GLIBC version directly in the executable filename for clarity.

**Comment by tom-rm-meyer-ISST** [comment]
Finally, upgraded and I can confirm: Ubuntu 22.04.03 LTS +  GLIBC 2.35 works fine for release 4.5.0 and 4.5.1. Thanks, a lot!

Wasn't sure, if the current release would already contain the version mentioned. 

If there's nothing further to do, we can close this issue, don't we?

**Comment by michelu89** [comment]
GLIBC version will be part of the filename in the new version > 4.5.2.
