### ISSUE TITLE
[BUG] Aspect Model Editor Validation identifies samm:characteristic twice even though it is only there one time

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-aspect-model-editor#58]
**Describe the bug**

<img width="953" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/13886571/e385baee-7ea1-476d-8d9a-010eff9c4f4e">

Problem can be varified with model
https://github.com/eclipse-tractusx/sldt-semantic-models/pull/221/files

The validation of the SAMM-CLI v2.2.2 does not give a problem
```
java -jar ~/Downloads/samm-cli-2.2.2.jar  aspect io.catenax.quality_task_attachment/1.0.0/QualityTaskAttachment.ttl validate
Input model is valid
```

**Where**
Aspect Model Editor 4.4.1

**Screenshots**

**Additional context**

**Comment by michelu89** [comment]
Hi @bs-jokri , when I load the mentioned Aspect Model into the Aspect Model Editor v4.4.1, it shows as valid for me. Could you provide more detailed information about this? Are there other Aspect Models in the workspace? Perhaps there's an Aspect Model listed there that contains the same elements.

**Comment by bs-jokri** [comment]
I checked the workspace. No model with elements with same name. I also removed all models from workspace. Still same problem
<img width="1392" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/13886571/c1342909-8386-4053-bef5-ff537d16e934">

**Comment by michelu89** [comment]
Aspect Model was not defined correctly. Issue is closed.
