### ISSUE TITLE
[Feature Request] Add Refresh button on the current Worskpace

### ISSUE THREAD

**Issue by Kostadin-Ivanov** [eclipse-esmf/esmf-aspect-model-editor#63]
when I work with the editor, sometimes I move manually files to and from its workspace.

For the moment, if the editor was open, while I was adding / removing a file / folder, I had to literally close the editor and open it again in order to pickup the changed workspace files and folders.

**REQUEST:** Would it be possible to have some kind of Refresh button, which we can click to reload/refresh the workspace without the need to Close&Open the editor everytime when we change the workspace?

**Further more, if possible**: add way to track the workspace structure state would be very handy while we work with the editor.

**For example:** 
I work with the editor and I have two folders with a ttl file within each model, similar to the ones below:
`aspect-model-editor/models/com.my.projectA/1.0.0/MyProjectAModel.ttl`
`aspect-model-editor/models/com.my.projectB/1.0.0/MyProjectBModel.ttl`

at some point, I decide to add a "library" with pre created  models, which I would like to reuse in my project's models.
The Editor is still open, while I add the aforementioned library, which will change my workspace to:

`aspect-model-editor/models/com.my.projectA/1.0.0/MyProjectAModel.ttl`
`aspect-model-editor/models/com.my.projectB/1.0.0/MyProjectBModel.ttl`
`aspect-model-editor/models/com.shared.models.library/3.0.1/ExampleModel.ttl`
`aspect-model-editor/models/com.shared.models.library/3.0.1/SomeOtherModel.ttl`
`aspect-model-editor/models/com.shared.models.library/3.0.1/...`

**The new functionality:** as soon as the folder structure of my workspace has been changed, either added / removed file(s) or folder(s), in our case I added a new folder with set of files, the workspace view in my Editor will get highlighted in some way: either a popup will be displayed, or if we don't want to interrupt user work, just highlight the workspace area on the left panel so user can see that there was some change with it, and the workspace needs to be reloaded / refreshed so to pickup the newly updated folder structure.

**Comment by Kostadin-Ivanov** [comment]
Today I was told, by a colleague about latest AME - 4.4.1, which had implemented the Workspace Refresh button.
I just tested it with latest - 4.4.1 version and it works fine.

Maybe as further improvement, we could get some kind of a notification about changed workspace or that a Refresh is needed.
Other than this I think that this request is already implemented and feel free to either close as **fixed upstream** or link this ticket to corresponding change.

Thank you.

**Comment by Kostadin-Ivanov** [comment]
Hello @chris-volk ,
please check my comment on this request, which seems to be already implemented since AME version 4.1.0 and advise on whether it is better to close it and open a "further improvement" task for suggested in my last comment behavior of the "Save" button.

Thank you in advance and well done for version 4.5.0 :)

**Comment by chris-volk** [comment]
Hi @Kostadin-Ivanov , thanks for the discussion and the detailed proposal. After discussing the technicals we have decided to not implement the further improvement of automatic refresh, so a manual refresh will be required after workspace changes.

**Comment by Kostadin-Ivanov** [comment]
Thank you @chris-volk , my idea was to: get a notification that the workspace has been changed, so user can manually refresh it.
Either by highlighting the "Workspace" title by making it or just the "Refresh button" in bold, or raise some prompt - message to user.
In order to reduce user's distraction maybe second option is not preferable but still could be considered.

Anyway, thank you for the great support so far and we will keep in touch with more ideas and observations from our side :)
