### ISSUE TITLE
[BUG] ENUMS with values with Datatype samm:curie cause exception even though the spec allows this and the SaMM-CLI validates this

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-aspect-model-editor#65]
**Describe the bug**
load model
https://github.com/eclipse-tractusx/sldt-semantic-models/pull/257/files#diff-8dc947ad5587c30180d8477c9e5cea7faf956d8d990ab3dedddfa1673d20cce4

with editor 4.4.1

error is thrown and enum with curie values is not properly processed

expectation: curie values are properly processed

**Comment by chris-volk** [comment]
raw file: https://raw.githubusercontent.com/eclipse-tractusx/sldt-semantic-models/b05aa6a441ea1a571eb4f34d77ac4a6b7ce75e4b/io.catenax.shared.shopfloor_information_types/1.0.0/ShopfloorInformationTypes.ttl
