### ISSUE TITLE
[Task] Alphanumeric sorting in workspace

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#68]
To organize my work as a user I need alphanumeric sorting of namespaces in the workspace.

The namespaces contain reverse domain notification, e.g. com.eclipse, com.eclipse.example.subexample:1.0.0, *1.0.1, *2.0.0 .
When I have many namespaces I need to see them grouped by topic and version to work in an organized way.

Hence, alphanumeric sorting.

**Comment by chris-volk** [comment]
Further ideas: 
- resizable panels
- option to abbreviate domains (e.g. c.b.d.ProductInstance)
- show additional ellipsis in middle for words >3chars?
- show prefix instead of namespace (caution, might create complexity, own namespace is empty, change this to create short name)

**Comment by michelu89** [comment]
This is already fixed. 

- Release Version 5.x.x
