### ISSUE TITLE
[BUG] Window title doesn't update after namespace change

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-esmf/esmf-aspect-model-editor#72]
**Describe the bug**

After changing the namespace in the Aspect Model Editor from the settings menu, the title of the AME window doesn't update properly.

**Where**
in the window title

**Screenshots**

**Additional context**
Observed in AME 4.4.0, Windows version

**Comment by jacewski-bosch** [comment]
I'd like to add a screenshot, but I get an undefined error from github. Will try to add later

**Comment by michelu89** [comment]
Fixed will be released on next version.
