### ISSUE TITLE
[BUG] Adding of an external property to a model, overlaps with the main Aspect node

### ISSUE THREAD

**Issue by Kostadin-Ivanov** [eclipse-esmf/esmf-aspect-model-editor#73]
**Describe the bug**
When working with multiple models in the AME and trying to add a property from "external" model, the drag&dropped property is positioned over my currently loaded model - Aspect node.
Thus it makes it hard to link the property to my model entity.

**Where**
In the AME during drag&drop of external properties.

**Screenshots**
Still having troubles with adding attachments here but if required, I can send them by email.

**Additional context**
Observed on AME version 4.5.0 - for Windows

**Comment by michelu89** [comment]
We've made adjustments to enhance the usability.

Please note that the overlapping issue is recognized in our ['known issues'](https://eclipse-esmf.github.io/ame-guide/support/known-issues.html) section.
Given the current constraints with the mx-graph library, addressing this is quite challenging. 
As such, we've decided to defer its resolution to a future update.
