### ISSUE TITLE
[BUG] Editor is losing focus when I hit the format editor button

### ISSUE THREAD

**Issue by Kostadin-Ivanov** [eclipse-esmf/esmf-aspect-model-editor#74]
**Describe the bug**
During work on a model with the AME and:
1. I add some external properties which make my model to expand on width
2. When I hit the "Format" button, while my "visible area" of the shows me, lets say the top of my model, i.e. its Aspect node
3.  Then after the model gets formatted my visible area gets blank, i.e. the root of the model, which before formatting was visible, got shifter to the right of the screen, making me to browse to it again, **instead of** to still be displayed, probably centered in my visible area of the editor.

**Where**
Aspect Model Editor

**Screenshots**
I've prepared two screenshots but for some reason I cannot add them to this ticket. However, if required, I can send them by email.

**Additional context**
Observed on AME 4.5.0 for Windows

**Comment by michelu89** [comment]
Will be available in version 5.1.2.
