### ISSUE TITLE
[BUG] Abstract property instances appear only once in visualization

### ISSUE THREAD

**Issue by jacewski-bosch** [eclipse-esmf/esmf-aspect-model-editor#76]
**Describe the bug**
When you model an abstract entity with abstract properties and have more than one entity extending it, only one instance of the abstract property is shown. Although two of them exist. This is confusing since, the instances have different characterstics attached to them. In the visualization it is thus not clear which property instance is described by which characteristic. Also it makes manipulation of these characteristics not possible in the editor.

**Where**
Visualization in the main window

**Screenshots**

I'd like to add screenshots but Github doesn't let me. :(

**Additional context**

To reproduce, import this Aspect in the Modeler (I observed it in 4.4.0, but would assume it's not fixed for newer versions).

Note how `ExtendingEntity1` as well as `ExtendingEntity2` both instantiate `abstractProperty4` with different Characterstics but in the graphical representation it is not clear which is attached to which.

```
@prefix samm: <urn:samm:org.eclipse.esmf.samm:meta-model:2.0.0#>.
@prefix samm-c: <urn:samm:org.eclipse.esmf.samm:characteristic:2.0.0#>.
@prefix samm-e: <urn:samm:org.eclipse.esmf.samm:entity:2.0.0#>.
@prefix unit: <urn:samm:org.eclipse.esmf.samm:unit:2.0.0#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix : <urn:samm:org.eclipse.digitaltwin:1.0.0#>.

:AspectDefault a samm:Aspect;
    samm:properties (:property1 :property2);
    samm:operations ();
    samm:events ().
:property1 a samm:Property;
    samm:characteristic :Characteristic1.
:property2 a samm:Property;
    samm:characteristic :Characteristic2.
:Characteristic1 a samm-c:SingleEntity;
    samm:dataType :ExtendingEntity1.
:Characteristic2 a samm-c:SingleEntity;
    samm:dataType :ExtendingEntity2.
:ExtendingEntity1 a samm:Entity;
    samm:properties ([
  samm:characteristic :Characteristic3;
  samm:extends :abstractProperty4
]);
    samm:extends :AbstractEntityWithTwoAbstractProperties.
:ExtendingEntity2 a samm:Entity;
    samm:properties ([
  samm:characteristic :Characteristic4;
  samm:extends :abstractProperty4
]);
    samm:extends :AbstractEntityWithTwoAbstractProperties.
:AbstractEntityWithTwoAbstractProperties a samm:AbstractEntity;
    samm:properties (:abstractProperty4).
:abstractProperty4 a samm:AbstractProperty.
:Characteristic3 a samm-c:Measurement;
    samm:dataType xsd:integer;
    samm-c:unit unit:metre.
:Characteristic4 a samm-c:Measurement;
    samm:dataType xsd:float;
    samm-c:unit unit:litre.

```

**Comment by chris-volk** [comment]
This is the model loaded into AME 4.5.0 (collapsed view):
<img width="715" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/f95769cf-26af-407a-941e-3997bfb23e1e">

**Comment by jacewski-bosch** [comment]
When uploading I get 

"Something went really wrong, and we can't process that file. Try again."

**Comment by jacewski-bosch** [comment]
Ok, I just checked and in  AME 4.5.0 and it is fixed. Closing this issue then.
