### ISSUE TITLE
[Task] Make wording and display of inheritance and references consistent and understandable

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#78]
<img width="482" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/46d69f64-e594-4720-b3a1-7b2c3500e21f">

Currently, the edit section of an Element offers a "Parents" section and a "Children" section to see the _referenced_ and the _referencing_ elements in a list (and allow to locate them).
However, for abstract entities and properties this is confusing since a) these are the parents and children with resepct to inheritance hierarchy and b) right now they are shown in the same list.

It is required to come up with differentiating wordings and a way to show these elements in different lists.

Idea: 
4 sections for "Referencing elements" | "References" | "Parents" | "Children", idea: show parents and chidlren as sections below (and hide them if empty)

**Comment by chris-volk** [comment]
FYI, the Teacher Person example from the SAMM spec (https://eclipse-esmf.github.io/samm-specification/2.0.0/modeling-guidelines.html#extending-entities ): 

<img width="612" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/6bbbc35a-95a9-4e6c-a956-9f486a079e27">

**Comment by chris-volk** [comment]
After discussion: outgoing and incoming edges have too many different semantic meanings, e.g. List Char -> element Char, extend, datatype, entity, ...

So, clustering into two categories is probably the better structure.
Parents/Children might mislead people into thinking that this is the inheritance hierarchy induced by "extends". 
To avoid that, the terms "Incoming" and "Outgoing" might be used.

**Comment by michelu89** [comment]
Fixed on https://github.com/eclipse-esmf/esmf-aspect-model-editor/releases/tag/v4.5.3
