### ISSUE TITLE
[BUG] Frontend (NPM, Linux, v4.5.x) does not support drag and drop

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-esmf/esmf-aspect-model-editor#80]
**Describe the bug**
The left pane used for the "Workspace" and modelling elements does NOT support support the drag and drop function into the modelling pane (right side). Both, reusing workspace model elements AND adding new model elements (such as AbstractEntity, Entity), can not be added.

**Where**
Frontend, Drag and Drop between left pane and main pane

**Screenshots**
![image](https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/116013795/84cf8f5b-08b9-45b7-ad86-8db0412d1b17)

**Additional context**
I am using Firefox (116.0.2) on Ubuntu (20.04.6 LTS, GNOME 3.36.8). The electron way of starting works technically BUT it requires the release version, which is not working for me as a workaround

**Comment by michelu89** [comment]
Hey @tom-rm-meyer-ISST

We have identified an issue with the draggable feature provided by MxGraph when used in Firefox. Addressing this requires a specialized analysis specific to Firefox. While it's not our top priority currently, any insight or contributions you can make towards resolving this would be greatly appreciated.

For a temporary solution:

* Use our latest Linux Electron version, or
* Switch to a Chromium-based browser where the drag and drop functionality has been extensively tested and confirmed to work. (Chrome, Chromium, etc.)

Thanks for your understanding and support.

**Comment by michelu89** [comment]
Issue will be closed. Please re-open if something is still missing.
