### ISSUE TITLE
[Task]  Show more children in edit panel & improve edit logo

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#85]
As a user I want to see as many children of an element in the edit view as possible without scrolling, 
hence the Children box should fully extend to the bottom of the screen (or end when the list is complete)
<img width="483" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/2b1a4d7f-7eca-4c17-a554-52b09fa39622">
(Screenshot from AME 4.5.2)

To easier understand that I can navigate step by step into children via what is currently called the "edit" option in a children row, 
it should better be called "Open element" with an appropriate icon like the "open in browser" from https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_browser:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=open .

Discussion and other opinions welcome.

**Comment by michelu89** [comment]
Will be part of the next release.
