### ISSUE TITLE
[BUG]: Save > Copy to Clipboard not working when model is not saved

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-esmf/esmf-aspect-model-editor#87]
**Describe the bug**
IF 
- I reuse a Characterisitc from Model A in Model B (or any other change)
- I have NOT yet saved Model B
- I save the model via "copy to clipboard"
THEN
- the external reference is ommitted (or any other change)

Note for reproduction: 
- start modelling using the default aspect
- rename the aspect property, confirm
- remove the characteristic 
- open workspace, select one model, pull one characteristic into modelling section
- trigger copy to clipboard action

**Note: that way I initially thought it removes external references. Enforcing a save to local storage solves the issue. Maybe this should be added to the copy to clipboard action.**
**Where**
Aspect Model > Save in Tooolbar > Copy to Clipboard
Other save options do work

**Screenshots**
None

**Additional context**
Aspect Model Editor version 4.5.1

Didn't try the 4.5.2 version as the changelog does not seem to have a change for the component.

**Comment by chris-volk** [comment]
Thanks for reporting, @tom-rm-meyer-ISST .
(You're right that 4.5.2 does not change the behavior.)
Your proposal is good and copy to clipboard should behave just like save "Export Aspect Model" following the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). We'll also consider to call it "Export to Clipboard" to indicate it's the same as "Export Aspect Model" - just with a different output format.

**Comment by tom-rm-meyer-ISST** [comment]
Highly appreciated!
