### ISSUE TITLE
[BUG] Cannot specify exampleValue true/false for Boolean Characteristic instance

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#94]
Create a minimal Aspect Model: One property with Characteristic Instance Boolean.
Specify true or false as example value.
Generate JSON Schema.

Expected: true/false (without strings) is generated as example value (as would be in json sample payload if no exampleValue is provided).

Actual: JSON Schema cannot be generated due to datatype mismatch.

Reason: Boolean is currently using datatype string, expected: boolean.

Applies to: AME 4.5.2

<img width="1058" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/03fb6b4b-41a5-4444-9fb2-10ea484e64fb">

**Comment by Kostadin-Ivanov** [comment]
Tested on AME version: 4.6.0 and expected dataType for a Boolean characteristic was: boolean as expected.

**Comment by michelu89** [comment]
Will be part of the next release.
