### ISSUE TITLE
[BUG] Robustness: Cannot select SAMM element for large models 

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-aspect-model-editor#99]
**How: List of performed steps**
- Load large model (~200-500 elements) where 1 element has many children (~50)
- try to modify one of the children by double clicking

**What: Actual result vs expected result**
- child element cannot be selected since it's overwritten by multiple edges (this prevents me from doing my job)
- edges are unintentionally selected (this is undesired)
- edges are unintentionally skewed (this is the worst since I cannot undo it)

- my expectation would be that an element is always in the foreground so that I can edit it (no matter whether I found it myself or located it via search)
- if that's not possible (since maybe multiple elements overlap each other) my expectation would be that I can open the edit dialog of a selected element (since I searched for it) no matter whether it's in the foremost layer or not

**Where: (e.g. component, version, url, your system info)**
AME 4.6.0, win10

**Input (files/screenshots)**

**Output (files/screenshots)**
<img width="1665" alt="image" src="https://github.com/eclipse-esmf/esmf-aspect-model-editor/assets/71717528/0d1ed464-c628-44cf-ae18-92ba3f765d8d">

**Additional context (e.g. references)**
Using search as a workaround doesnt help, it let's me focus an element, but not open the edit box

**Comment by michelu89** [comment]
@chris-volk Current solution in version 5.1.1 is that the arrows are displayed in the background and the elements can be opened.
